apiVersion: v1
kind: Service
metadata:
  name: edf-consumption-predictor-service-local
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: edf-consumption-predictor
