apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edf-consumption-predictor-hpa
  namespace: edf-rte-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edf-consumption-predictor-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
